/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-19 08:14:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/Uni/Java/SICT_Web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SICT_Web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1747295768479L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assets/fonts/themify-icons/themify-icons.css\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Container để căn giữa */\r\n");
      out.write("        .navbar-container {\r\n");
      out.write("            max-width: 1200px; /* Giới hạn chiều rộng tối đa */\r\n");
      out.write("            margin: 0 auto; /* Căn giữa */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Thanh điều hướng */\r\n");
      out.write("        .navbar {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            background-color: #003366;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar > li {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar > li > a {\r\n");
      out.write("            display: block;\r\n");
      out.write("            padding: 10px 12px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar > li:hover {\r\n");
      out.write("            background-color: #005599;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Dropdown menu */\r\n");
      out.write("        .dropdown {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 100%;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            min-width: 200px;\r\n");
      out.write("            display: none;\r\n");
      out.write("            padding: 5px 0;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.15);\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown li a {\r\n");
      out.write("            display: block;\r\n");
      out.write("            padding: 8px 15px;\r\n");
      out.write("            color: #003366;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropdown li a:hover {\r\n");
      out.write("            background-color: #f0f0f0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .submenu {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 100%;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            min-width: 200px;\r\n");
      out.write("            display: none;\r\n");
      out.write("            padding: 5px 0;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.15);\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .submenu li a {\r\n");
      out.write("            display: block;\r\n");
      out.write("            padding: 8px 15px;\r\n");
      out.write("            color: #003366;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .submenu li a:hover {\r\n");
      out.write("            background-color: #f0f0f0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Hiện dropdown khi hover */\r\n");
      out.write("        .navbar > li:hover > .dropdown {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Hiện submenu của \"ĐẠI HỌC\" khi hover vào mục \"ĐẠI HỌC\" trong dropdown \"ĐÀO TẠO\" */\r\n");
      out.write("        .navbar > li:nth-child(3) > .dropdown > li:first-child:hover > .submenu {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Hiện submenu của \"SAU ĐẠI HỌC\" khi hover vào mục \"SAU ĐẠI HỌC\" trong dropdown \"ĐÀO TẠO\" */\r\n");
      out.write("        .navbar > li:nth-child(3) > .dropdown > li:nth-child(2):hover > .submenu {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Logo and Title */\r\n");
      out.write("        .logobar {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            background-color: #f5f5f5;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            min-height: 60px; /* Match logo height */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo-title {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logobar img {\r\n");
      out.write("            height: 60px;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logobar h1 {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            color: #003366;\r\n");
      out.write("            line-height: 60px; /* Align vertically with logo */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* User login/logout */\r\n");
      out.write("        .user-menu {\r\n");
      out.write("            display: block; /* Hidden by default */\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logobar:hover .user-menu {\r\n");
      out.write("            display: block; /* Show on hover over logobar */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-menu a, .user-menu .dropdown-toggle {\r\n");
      out.write("            color: #003366;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            padding: 8px 12px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-menu .btn-login {\r\n");
      out.write("            background-color: #005599;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-menu:hover .dropdown-toggle {\r\n");
      out.write("            background-color: #e0e0e0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-menu .dropdown-menu {\r\n");
      out.write("            min-width: 150px;\r\n");
      out.write("            margin-top: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-menu .dropdown-menu a {\r\n");
      out.write("            color: #003366;\r\n");
      out.write("            padding: 8px 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-menu .dropdown-menu a:hover {\r\n");
      out.write("            background-color: #f0f0f0;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"logobar\">\r\n");
      out.write("        <div class=\"logo-title\">\r\n");
      out.write("            <img src=\"");
      out.print( request.getContextPath() );
      out.write("/images/logo.png\" alt=\"Logo HaUI\">\r\n");
      out.write("            <h1>TRƯỜNG CÔNG NGHỆ THÔNG TIN</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- User Login/Logout -->\r\n");
      out.write("        <div class=\"user-menu\">\r\n");
      out.write("            ");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                ");
          //  c:when
          org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
          _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
          _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
          // /header.jsp(202,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.USER}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
          int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
          if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("                    <a href=\"#\" class=\"dropdown-toggle\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
              out.write("                        <i class=\"bi bi-person-circle me-1\"></i>");
              if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
                return;
              out.write("\r\n");
              out.write("                    </a>\r\n");
              out.write("                    <ul class=\"dropdown-menu dropdown-menu-end\">\r\n");
              out.write("                        <li><a class=\"dropdown-item\" href=\"");
              out.print( request.getContextPath() );
              out.write("/user/logout\">Đăng xuất</a></li>\r\n");
              out.write("                    </ul>\r\n");
              out.write("                ");
              int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
          _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
          out.write("\r\n");
          out.write("                ");
          //  c:otherwise
          org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
          _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
          _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
          int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
          if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("                    <a href=\"");
              out.print( request.getContextPath() );
              out.write("/user/login\" class=\"btn btn-sm btn-login\">\r\n");
              out.write("                        <i class=\"bi bi-box-arrow-in-right me-1\"></i>Đăng nhập\r\n");
              out.write("                    </a>\r\n");
              out.write("                ");
              int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
          _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
          out.write("\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"navbar-container\">\r\n");
      out.write("        <ul class=\"navbar\">\r\n");
      out.write("            <li><a href=\"https://www.haui.edu.vn/vn\">TRANG HAUI</a></li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\">GIỚI THIỆU <i class=\"bi bi-chevron-down ms-auto\"></i></a>\r\n");
      out.write("                <ul class=\"dropdown\">\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/gioi_thieu\">THÔNG TIN CHUNG</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/gioi_thieu?cat=co_cau_to_chuc\">CƠ CẤU TỔ CHỨC</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/gioi_thieu?cat=chien_luoc_phat_trien\">CHIẾN LƯỢC PHÁT TRIỂN</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/gioi_thieu?cat=can_bo_giang_vien\">CÁN BỘ GIẢNG VIÊN</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/gioi_thieu?cat=co_so_vat_chat\">CƠ SỞ VẬT CHẤT</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/gioi_thieu?cat=lien_he\">LIÊN HỆ</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\">ĐÀO TẠO <i class=\"bi bi-chevron-down ms-auto\"></i></a>\r\n");
      out.write("                <ul class=\"dropdown\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">ĐẠI HỌC</a>\r\n");
      out.write("                        <ul class=\"submenu\">\r\n");
      out.write("                            <li class=\"submenu-item\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/dao_tao?cat=khoa_hoc_may_tinh\">KHOA HỌC MÁY TÍNH</a></li>\r\n");
      out.write("                            <li class=\"submenu-item\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/dao_tao?cat=ky_thuat_phan_mem\">KỸ THUẬT PHẦN MỀM</a></li>\r\n");
      out.write("                            <li class=\"submenu-item\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/dao_tao?cat=he_thong_thong_tin\">HỆ THỐNG THÔNG TIN</a></li>\r\n");
      out.write("                            <li class=\"submenu-item\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/dao_tao?cat=cong_nghe_thong_tin\">CÔNG NGHỆ THÔNG TIN</a></li>\r\n");
      out.write("                            <li class=\"submenu-item\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/dao_tao?cat=cong_nghe_da_phuong_tien\">CÔNG NGHỆ ĐA PHƯƠNG TIỆN</a></li>\r\n");
      out.write("                            <li class=\"submenu-item\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/dao_tao?cat=an_toan_thong_tin\">AN TOÀN THÔNG TIN</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">SAU ĐẠI HỌC</a>\r\n");
      out.write("                        <ul class=\"submenu\">\r\n");
      out.write("                            <li class=\"submenu-item\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/dao_tao?cat=sau_he_thong_thong_tin\">HỆ THỐNG THÔNG TIN</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/dao_tao?cat=quy_che_bieu_mau\">QUY CHẾ, BIỂU MẪU</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\">TUYỂN SINH <i class=\"bi bi-chevron-down ms-auto\"></i></a>\r\n");
      out.write("                <ul class=\"dropdown\">\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/tuyen-sinh-dai-hoc\">ĐẠI HỌC</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/tuyen-sinh-sau-dai-hoc\">SAU ĐẠI HỌC</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\">KHOA <i class=\"bi bi-chevron-down ms-auto\"></i></a>\r\n");
      out.write("                <ul class=\"dropdown\">\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/khoa?cat=cong_nghe_thong_tin\">KHOA CÔNG NGHỆ THÔNG TIN</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/khoa?cat=cong_nghe_phan_mem\">KHOA CÔNG NGHỆ PHẦN MỀM</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/khoa?cat=khoa_hoc_may_tinh\">KHOA KHOA HỌC MÁY TÍNH</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/khoa?cat=mang_may_tinh\">KHOA MẠNG MÁY TÍNH VÀ TRUYỀN THÔNG</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\">PHÒNG/TRUNG TÂM <i class=\"bi bi-chevron-down ms-auto\"></i></a>\r\n");
      out.write("                <ul class=\"dropdown\">\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/phong_trungtam?cat=tong_hop\">PHÒNG TỔNG HỢP</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/phong_trungtam?cat=hop_tac_phat_trien\">TRUNG TÂM HỢP TÁC PHÁT TRIỂN</a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/phong_trungtam?cat=nghien_cuu_ict\">TRUNG TÂM NGHIÊN CỨU CÔNG NGHỆ TIÊN TIẾN ICT</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
    // /header.jsp(204,64) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.USER.fullName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }
}
